export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as Products } from "./Products"
export { default as Product } from "./Product"
export { default as Home } from "./Home"
export { default as NotFound } from "./NotFound"
export { default as Checkout } from "./Checkout"
